services:
  webapp:
    build: ./WEBAPP
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173
    develop:
      watch:
        - action: sync
          path: ./WEBAPP
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - api
  api:
    build: ./API
    ports:
      - "8080:80"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/forum?authSource=admin
    develop:
      watch:
        - action: sync+restart
          path: ./API
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
volumes:
  mongodb_data:
