services:
  api:
    build: ./API
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/forum?authSource=admin
    develop:
      watch:
        - action: sync+restart
          path: ./API
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - mongodb
    expose:
      - "80"
    networks:
      - internal_net
  thread:
    build: ./THREAD
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:80
    depends_on:
      - api
    develop:
      watch:
        - action: sync+restart
          path: ./THREAD
          target: /app
          ignore:
            - node_modules/
    networks:
      - public_net
      - internal_net
  sender:
    build: ./SENDER
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:80
    depends_on:
      - api
    networks:
      - public_net
      - internal_net
  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - internal_net
volumes:
  mongodb_data:
networks:
  public_net: {}
  internal_net:
    internal: true
